### Send Request for city name

GET http://localhost:3001/api/geolocation?latitude=48.135125&longitude=11.581981
Content-Type: application/json
Authorization: {{$dotenv MAPQUEST_API_KEY}}

### Send Request for weather data
GET https://weatherapi-com.p.rapidapi.com/current.json?q=48.135125%2C11.581981

Content-Type: application/json
x-rapidapi-host: weatherapi-com.p.rapidapi.com
x-rapidapi-key: ab19c0a896msheb3a462deb88ee5p106d0ajsn0dca9ec220f2